'use strict';
// Mail-Strings der Templates, je Locale. Eigene Datei, weil die beiden
// Woerterbuecher zusammen laenger sind als der Render-Code drumherum und bei
// jedem neuen Template weiter wachsen — das Modul daneben soll deshalb nicht
// mit ihnen wachsen (Muster wie lib/app-settings.js + lib/app-settings/).
//
// Job-Error-Keys (z.B. job.error.phase1Incomplete) stehen NICHT hier, sondern
// in public/js/i18n/*.json — sie erscheinen auch im UI, und eine zweite Kopie
// wuerde driften. Aufgeloest werden sie ueber lib/i18n-server.js.

const TEXT = {
  de: {
    'mail.subject.invite':                   'Einladung zu {appName}',
    'mail.subject.inviteReminder':           'Erinnerung: Deine Einladung zu {appName}',
    'mail.subject.test':                     'Testmail von {appName}',
    'mail.body.invite.intro':                '{inviterName} hat dich zu {appName} eingeladen.',
    'mail.body.invite.cta':                  'Über folgenden Link kannst du dich anmelden:',
    'mail.body.invite.expires':              'Der Einladungslink ist gültig bis {expiresAt}.',
    'mail.body.invite.footer':               'Falls du diese Mail nicht erwartet hast, kannst du sie ignorieren.',
    'mail.body.inviteReminder.intro':        'Erinnerung: {inviterName} hat dich zu {appName} eingeladen, du hast die Einladung aber noch nicht angenommen.',
    'mail.body.inviteReminder.cta':          'Hier ist der Link nochmals:',
    // Lokale Anmeldung: Passwort setzen / zuruecksetzen.
    'mail.subject.passwordSet':              'Passwort für {appName} festlegen',
    'mail.subject.passwordReset':            'Passwort für {appName} zurücksetzen',
    'mail.body.passwordSet.intro':           'Für dein Konto bei {appName} kann jetzt ein Passwort festgelegt werden.',
    'mail.body.passwordSet.cta':             'Passwort über folgenden Link setzen:',
    'mail.body.passwordReset.intro':         'Für dein Konto bei {appName} wurde ein neues Passwort angefordert.',
    'mail.body.passwordReset.cta':           'Neues Passwort über folgenden Link setzen:',
    'mail.body.password.expires':            'Der Link ist gültig bis {expiresAt} und funktioniert nur einmal.',
    'mail.body.password.footer':             'Hast du das nicht angefordert, ignoriere diese Mail — dein bisheriges Passwort bleibt gültig.',
    'mail.body.test.intro':                  'Diese Mail bestätigt, dass {appName} Mails versenden kann.',
    'mail.body.test.config':                 'Konfiguration: {mode} über {fromEmail}.',
    // Registrierungs-Workflow.
    'mail.subject.registrationRequestAdmin': 'Neue Zugangs-Anfrage: {email}',
    'mail.subject.registrationApproved':     'Dein Zugang zu {appName} wurde freigeschaltet',
    'mail.subject.registrationDenied':       'Deine Zugangs-Anfrage zu {appName}',
    'mail.body.regReqAdmin.intro':           'Eine neue Zugangs-Anfrage liegt vor:',
    'mail.body.regReqAdmin.email':           'E-Mail: {email}',
    'mail.body.regReqAdmin.name':            'Name: {displayName}',
    'mail.body.regReqAdmin.source':          'Herkunft: {source}',
    'mail.body.regReqAdmin.sourceNote':      'Selbstauskunft: {sourceNote}',
    'mail.body.regReqAdmin.message':         'Nachricht:',
    'mail.body.regReqAdmin.meta':            'IP: {ip} · Zeit: {createdAt}',
    'mail.body.regReqAdmin.cta':             'Verwalten in der Admin-Konsole:',
    'mail.body.regApproved.intro':           'Dein Zugang zu {appName} wurde freigeschaltet.',
    'mail.body.regApproved.cta':             'Bitte melde dich über folgenden Link an:',
    'mail.body.regApproved.expires':         'Der Einladungslink ist bis {expiresAt} gültig.',
    'mail.body.regDenied.intro':             'Deine Zugangs-Anfrage zu {appName} wurde leider abgelehnt.',
    'mail.body.regDenied.reason':            'Begründung: {reason}',
    'mail.body.regDenied.footer':            'Bei Rückfragen wende dich an den Administrator.',
    // Buch-Share-Benachrichtigung.
    'mail.subject.bookShared':               '{appName}: Du wurdest zu „{bookName}" hinzugefügt',
    'mail.body.bookShared.intro':            '{inviterName} hat dich als {roleLabel} zu „{bookName}" hinzugefügt.',
    'mail.body.bookShared.cta':              'Buch in {appName} öffnen:',
    'mail.body.bookShared.noUrl':            'Melde dich in {appName} an, um das Buch zu öffnen.',
    'mail.body.bookShared.footer':           'Falls du diese Mail nicht erwartet hast, kannst du sie ignorieren.',
    'mail.body.bookShared.role.viewer':      'Leser',
    'mail.body.bookShared.role.lektor':      'Lektor',
    'mail.body.bookShared.role.editor':      'Editor',
    // Beta-Leser-Feedback (Share-Link-Kommentar).
    'mail.subject.shareComment':             '{appName}: Neues Feedback zu „{targetName}"',
    'mail.body.shareComment.intro':          '{readerName} hat „{targetName}" ({bookName}) kommentiert.',
    'mail.body.shareComment.introAnon':      'Ein Leser hat „{targetName}" ({bookName}) kommentiert.',
    'mail.body.shareComment.reply':          '{readerName} hat auf einen Thread zu „{targetName}" geantwortet.',
    'mail.body.shareComment.replyAnon':      'Ein Leser hat auf einen Thread zu „{targetName}" geantwortet.',
    'mail.body.shareComment.quote':          'Markierte Stelle:',
    'mail.body.shareComment.comment':        'Kommentar:',
    'mail.body.shareComment.cta':            'In {appName} ansehen:',
    'mail.body.shareComment.footer':         'Weitere neue Kommentare dieser Lese-Sitzung lösen vorerst keine weitere Mail aus. Du kannst diese Benachrichtigungen in den Mail-Einstellungen abschalten.',
    'mail.subject.shareReply':               'Neue Antwort zu „{targetName}"',
    'mail.body.shareReply.intro':            '{authorName} hat auf deinen Kommentar zu „{targetName}" ({bookName}) geantwortet.',
    'mail.body.shareReply.introAnon':        'Es gibt eine neue Antwort auf deinen Kommentar zu „{targetName}" ({bookName}).',
    'mail.body.shareReply.quote':            'Deine markierte Stelle:',
    'mail.body.shareReply.reply':            'Antwort:',
    'mail.body.shareReply.cta':              'Antwort ansehen und weiter mitreden:',
    'mail.body.shareReply.footer':           'Du erhältst diese Mail, weil du beim Kommentieren eine Adresse hinterlassen hast. Antworte direkt im geteilten Dokument.',
    // Job-Fail-Admin.
    'mail.subject.jobFailedAdmin':           '{appName}: Job-Fehler — {jobType}',
    'mail.body.jobFailedAdmin.intro':        'Ein Hintergrund-Job ist fehlgeschlagen.',
    'mail.body.jobFailedAdmin.fields':       'Job-Typ: {jobType}',
    'mail.body.jobFailedAdmin.user':         'User: {userEmail}',
    'mail.body.jobFailedAdmin.book':         'Buch: {bookName} (#{bookId})',
    'mail.body.jobFailedAdmin.error':        'Fehler: {errorMsg}',
    'mail.body.jobFailedAdmin.model':        'Modell: {provider}/{model}',
    'mail.body.jobFailedAdmin.tokens':       'Tokens: {tokensIn}↑ / {tokensOut}↓',
    'mail.body.jobFailedAdmin.duration':     'Dauer: {duration}',
    'mail.body.jobFailedAdmin.jobId':        'Job-ID: {jobId}',
    'mail.body.jobFailedAdmin.stackHeader':  'Stacktrace:',
    'mail.body.jobFailedAdmin.logHeader':    'Job-Log:',
    // Token-Cap-Admin.
    'mail.subject.tokenCapHitAdmin':         '{appName}: Token-Cap erreicht — {jobType}',
    'mail.body.tokenCapHitAdmin.intro':      'Ein Job wurde wegen Erreichen des Token-Caps abgebrochen.',
    'mail.body.tokenCapHitAdmin.hint':       'Erhöhe `ai.claude.max_tokens_out` in den Admin-Einstellungen (bzw. das Provider-Pendant `ai.ollama.max_tokens_out` / `ai.openai-compat.max_tokens_out`) oder zerlege das Buch in kleinere Kapitel.',
    // Budget-Overrun.
    'mail.subject.budgetOverrunUser':        '{appName}: Monatsbudget erreicht',
    'mail.subject.budgetOverrunAdmin':       '{appName}: Budget-Overrun — {userEmail}',
    'mail.body.budgetOverrun.intro':         'Das Monatsbudget für {userEmail} wurde im Zeitraum {period} überschritten.',
    'mail.body.budgetOverrun.usage':         'Verbrauch: {usd} USD von {budget} USD',
    'mail.body.budgetOverrun.modeSoft':      'Modus: Soft — KI-Calls laufen weiter, dies ist nur eine Warnung.',
    'mail.body.budgetOverrun.modeHard':      'Modus: Hard — neue KI-Calls werden bis zum Monatswechsel blockiert.',
    'mail.body.budgetOverrun.userIntro':     'Dein Monatsbudget bei {appName} wurde überschritten.',
    'mail.body.budgetOverrun.footer':        'Diese Mail wird einmal pro Monat verschickt.',
  },
  en: {
    'mail.subject.invite':                   'Invitation to {appName}',
    'mail.subject.inviteReminder':           'Reminder: your invitation to {appName}',
    'mail.subject.test':                     'Test email from {appName}',
    'mail.body.invite.intro':                '{inviterName} has invited you to {appName}.',
    'mail.body.invite.cta':                  'Use the following link to sign in:',
    'mail.body.invite.expires':              'The invitation link is valid until {expiresAt}.',
    'mail.body.invite.footer':               'If you did not expect this email you can simply ignore it.',
    'mail.body.inviteReminder.intro':        'Reminder: {inviterName} invited you to {appName} but you have not accepted yet.',
    'mail.body.inviteReminder.cta':          'Here is the link again:',
    'mail.subject.passwordSet':              'Set your password for {appName}',
    'mail.subject.passwordReset':            'Reset your password for {appName}',
    'mail.body.passwordSet.intro':           'You can now set a password for your {appName} account.',
    'mail.body.passwordSet.cta':             'Set your password via the following link:',
    'mail.body.passwordReset.intro':         'A new password was requested for your {appName} account.',
    'mail.body.passwordReset.cta':           'Set a new password via the following link:',
    'mail.body.password.expires':            'The link is valid until {expiresAt} and works only once.',
    'mail.body.password.footer':             'If you did not request this, ignore this email — your current password stays valid.',
    'mail.body.test.intro':                  'This message confirms that {appName} can send mail.',
    'mail.body.test.config':                 'Configuration: {mode} via {fromEmail}.',
    'mail.subject.registrationRequestAdmin': 'New access request: {email}',
    'mail.subject.registrationApproved':     'Your access to {appName} has been approved',
    'mail.subject.registrationDenied':       'Your access request for {appName}',
    'mail.body.regReqAdmin.intro':           'A new access request has arrived:',
    'mail.body.regReqAdmin.email':           'Email: {email}',
    'mail.body.regReqAdmin.name':            'Name: {displayName}',
    'mail.body.regReqAdmin.source':          'Came from: {source}',
    'mail.body.regReqAdmin.sourceNote':      'Self-reported: {sourceNote}',
    'mail.body.regReqAdmin.message':         'Message:',
    'mail.body.regReqAdmin.meta':            'IP: {ip} · Time: {createdAt}',
    'mail.body.regReqAdmin.cta':             'Manage in the admin console:',
    'mail.body.regApproved.intro':           'Your access to {appName} has been approved.',
    'mail.body.regApproved.cta':             'Please sign in via the following link:',
    'mail.body.regApproved.expires':         'The invitation link is valid until {expiresAt}.',
    'mail.body.regDenied.intro':             'Your access request for {appName} has been declined.',
    'mail.body.regDenied.reason':            'Reason: {reason}',
    'mail.body.regDenied.footer':            'Please reach out to the administrator with any questions.',
    'mail.subject.bookShared':               '{appName}: you were added to "{bookName}"',
    'mail.body.bookShared.intro':            '{inviterName} added you as {roleLabel} to "{bookName}".',
    'mail.body.bookShared.cta':              'Open the book in {appName}:',
    'mail.body.bookShared.noUrl':            'Sign in to {appName} to open the book.',
    'mail.body.bookShared.footer':           'If you did not expect this email you can simply ignore it.',
    'mail.body.bookShared.role.viewer':      'Reader',
    'mail.body.bookShared.role.lektor':      'Proof-reader',
    'mail.body.bookShared.role.editor':      'Editor',
    'mail.subject.shareComment':             '{appName}: new feedback on "{targetName}"',
    'mail.body.shareComment.intro':          '{readerName} commented on "{targetName}" ({bookName}).',
    'mail.body.shareComment.introAnon':      'A reader commented on "{targetName}" ({bookName}).',
    'mail.body.shareComment.reply':          '{readerName} replied to a thread on "{targetName}".',
    'mail.body.shareComment.replyAnon':      'A reader replied to a thread on "{targetName}".',
    'mail.body.shareComment.quote':          'Highlighted passage:',
    'mail.body.shareComment.comment':        'Comment:',
    'mail.body.shareComment.cta':            'View in {appName}:',
    'mail.body.shareComment.footer':         'Further comments from this reading session will not trigger another email for now. You can disable these notifications in the mail settings.',
    'mail.subject.shareReply':               'New reply on "{targetName}"',
    'mail.body.shareReply.intro':            '{authorName} replied to your comment on "{targetName}" ({bookName}).',
    'mail.body.shareReply.introAnon':        'There is a new reply to your comment on "{targetName}" ({bookName}).',
    'mail.body.shareReply.quote':            'Your highlighted passage:',
    'mail.body.shareReply.reply':            'Reply:',
    'mail.body.shareReply.cta':              'View the reply and keep the conversation going:',
    'mail.body.shareReply.footer':           'You receive this email because you left an address when commenting. Reply directly in the shared document.',
    'mail.subject.jobFailedAdmin':           '{appName}: job failed — {jobType}',
    'mail.body.jobFailedAdmin.intro':        'A background job has failed.',
    'mail.body.jobFailedAdmin.fields':       'Job type: {jobType}',
    'mail.body.jobFailedAdmin.user':         'User: {userEmail}',
    'mail.body.jobFailedAdmin.book':         'Book: {bookName} (#{bookId})',
    'mail.body.jobFailedAdmin.error':        'Error: {errorMsg}',
    'mail.body.jobFailedAdmin.model':        'Model: {provider}/{model}',
    'mail.body.jobFailedAdmin.tokens':       'Tokens: {tokensIn}↑ / {tokensOut}↓',
    'mail.body.jobFailedAdmin.duration':     'Duration: {duration}',
    'mail.body.jobFailedAdmin.jobId':        'Job ID: {jobId}',
    'mail.body.jobFailedAdmin.stackHeader':  'Stack trace:',
    'mail.body.jobFailedAdmin.logHeader':    'Job log:',
    'mail.subject.tokenCapHitAdmin':         '{appName}: token cap hit — {jobType}',
    'mail.body.tokenCapHitAdmin.intro':      'A job was aborted because the output-token cap was reached.',
    'mail.body.tokenCapHitAdmin.hint':       'Increase `ai.claude.max_tokens_out` in the admin settings (or the provider-specific `ai.ollama.max_tokens_out` / `ai.openai-compat.max_tokens_out`), or split the book into smaller chapters.',
    'mail.subject.budgetOverrunUser':        '{appName}: monthly budget reached',
    'mail.subject.budgetOverrunAdmin':       '{appName}: budget overrun — {userEmail}',
    'mail.body.budgetOverrun.intro':         'The monthly budget for {userEmail} has been exceeded in period {period}.',
    'mail.body.budgetOverrun.usage':         'Usage: {usd} USD of {budget} USD',
    'mail.body.budgetOverrun.modeSoft':      'Mode: Soft — AI calls keep running, this is just a warning.',
    'mail.body.budgetOverrun.modeHard':      'Mode: Hard — new AI calls are blocked until the month rolls over.',
    'mail.body.budgetOverrun.userIntro':     'Your monthly budget on {appName} has been exceeded.',
    'mail.body.budgetOverrun.footer':        'This notification is sent at most once per month.',
  },
};

module.exports = { TEXT };
